### ISSUE TITLE
Auto Run feature?

### ISSUE THREAD

**Issue by ghost** [jodoglevy/TriviaCracker#1]
Hi there,

I made a very similar script, however mine is more of a bot that sits and watches out for games and then auto completes it for you. In other words, no GUI to make it look nice. Any chance of you doing an auto run on your game? Theres plenty of more vulns in this API that weren't mentioned in your blog post. If you are interested of course..

**Comment by JAL9302** [comment]
What are the other vulnerabilities? I could be interested.

On Tue, Feb 17, 2015 at 4:27 AM, pslifeisgood notifications@github.com
wrote:

> Hi there,
> 
> I made a very similar script, however mine is more of a bot that sits and
> watches out for games and then auto completes it for you. In other words,
> no GUI to make it look nice. Any chance of you doing an auto run on your
> game? Theres plenty of more vulns in this API that weren't mentioned in
> your blog post. If you are interested of course..
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jodoglevy/TriviaCracker/issues/1.

## 

_Joe Levy_
Duke University '12, Computer Science
www.jodoglevy.com
919.886.6563

**Comment by ghost** [comment]
It would be easier to private message about this, any methods you use?

**Comment by JAL9302** [comment]
My email is on jodoglevy.com. Can you email me?
